TOPLEVEL_LANG ?= verilog
SIM ?= icarus
VERILOG_SOURCES = $(shell pwd)/adder.sv
TOPLEVEL := adder # Verilog or SystemVerilog TOP file module name
MODULE   := adder_tb # Python file name


include $(shell cocotb-config --makefiles)/Makefile.sim
